--- # Ansible Playbook to configure a set of Raspberry PIs in a consistent and repeatable way
# Software installation and configuration
- hosts: security_service
  remote_user: "{{ user }}"
  become: yes
  become_user: "{{ user }}"
  vars:
    src_dir: "{{ playbook_dir }}"
    mode: u=rwx
  vars_files:
    - "{{ src_dir }}/conf/config.yaml"
  tasks:
    #################################################################
    ##### Windfire Security server component deployment Section #####
    #################################################################
    # Task 1: Stop Windfire Security service on remote server
    - name: Get PID for running process "{{ process }}"
      shell: "pgrep -f {{ process }}"
      register: app_pid
      failed_when: app_pid.rc > 1
    
    - name: Kill "{{ process }}" process gracefully
      shell: "kill -TERM {{ item }}"
      with_items: "{{ app_pid.stdout_lines }}"
      when: app_pid.rc == 0
      register: kill_result
      failed_when:
        - kill_result.rc != 0
        - '"No such process" not in kill_result.stderr'

    - name: Wait for "{{ process }}" process graceful termination
      wait_for:
        path: "/proc/{{ item }}/status"
        state: absent
      with_items: "{{ app_pid.stdout_lines }}"
      when: app_pid.rc == 0
      ignore_errors: yes

    # Task 2: Delete Windfire Security directory on remote server
    - name: Remove "{{ remote_windfire_security_dir }}" directory and all its contents on remote server 
      ansible.builtin.file:
        path: "{{ remote_windfire_security_dir }}"
        state: absent
    
    # Task 3: Create Windfire Security directory on remote server and copy files
    - name: Copy Windfire Security server component to "{{ remote_windfire_security_dir }}" directory on remote server
      ansible.builtin.synchronize:
        src: "../../server"
        dest: "{{ remote_windfire_security_dir }}"
        rsync_opts:
          - "--exclude=windfire-security-server"
          - "--exclude=__pycache__"
          - "--exclude=config/service_config.json_PLACEHOLDER"
          - "--exclude=ssl/windfire-security.crt"
          - "--exclude=ssl/windfire-security.key"
          - "--exclude=.env_PLACEHOLDER"
          - "--exclude=windfire-security-server.log*"
    
    # Task 4: Copy SSL certificate and key to remote server
    - name: Copy certificate {{ windfire_server_certificate }} from {{ local_certs_dir }} to "{{ remote_windfire_security_dir }}/server/ssl" directory on remote server
      copy:
        src: "{{ local_certs_dir }}/{{ windfire_server_certificate }}"
        dest: "{{ remote_windfire_security_dir }}/server/ssl"
        owner: "{{ user }}"
        group: "{{ group }}"
        mode: "{{ mode }}"
    - name: Copy key {{ windfire_server_key }} from {{ local_certs_dir }} to "{{ remote_windfire_security_dir }}/server/ssl" directory on remote server
      copy:
        src: "{{ local_certs_dir }}/{{ windfire_server_key }}"
        dest: "{{ remote_windfire_security_dir }}/server/ssl"
        owner: "{{ user }}"
        group: "{{ group }}"
        mode: "{{ mode }}"

    # Task 5: Copy setenv.sh to remote server
    - name: Copy setenv.sh to "{{ remote_windfire_security_dir }}" directory on remote server
      copy:
        src: "../../setenv.sh"
        dest: "{{ remote_windfire_security_dir }}"
        owner: "{{ user }}"
        group: "{{ group }}"
        mode: "{{ mode }}"
    
    # Task 6: Copy commons.sh to remote server
    - name: Copy commons.sh to "{{ remote_windfire_security_dir }}" directory on remote server
      copy:
        src: "../../commons.sh"
        dest: "{{ remote_windfire_security_dir }}"
        owner: "{{ user }}"
        group: "{{ group }}"
        mode: "{{ mode }}"

    # Task 7: Ensure remote truststore directory exists and copy Windfire Root CA certificate
    - name: Ensure remote truststore directory {{ remote_truststore_dir }} exists
      file:
        path: "{{ remote_truststore_dir }}"
        state: directory
        owner: "{{ user }}"
        group: "{{ group }}"
        mode: "{{ mode }}"
        recurse: yes
    - name: Copy {{ windfire_ca_root_certificate }} to "{{ remote_truststore_dir }}" directory on remote server
      copy:
        src: "../../ssl/{{ windfire_ca_root_certificate }}"
        dest: "{{ remote_truststore_dir }}"
        owner: "{{ user }}"
        group: "{{ group }}"
        mode: "{{ mode }}"

    # Task 8: Create Python virtual environment
    - name: Create Python virtual environment
      command:
        cmd: "{{ python_interpreter }} -m venv {{ venv_path }}"
        creates: "{{ venv_path }}/bin/activate"

    # Task 9: Verify virtualenv installation
    - name: Verify virtualenv is properly configured
      shell:
        cmd: "source {{ venv_path }}/bin/activate && python --version"
        executable: /bin/bash
      register: python_version
      changed_when: false
    - name: Display Python version in virtualenv
      debug:
        msg: "Python version in virtualenv: {{ python_version.stdout }}"
    
    # Task 10: Install required Python modules in virtualenv
    - name: Install required Python modules in virtualenv by running {{ install_python_modules_script }} install script
      shell: |
        source {{ venv_path }}/bin/activate
        bash {{ remote_windfire_security_dir }}/server/{{ install_python_modules_script }}
      args:
        executable: /bin/bash
      
    # Task 11: List installed packages
    - name: List installed packages in virtualenv
      shell:
        cmd: "{{ venv_path }}/bin/pip list"
      register: pip_list
      changed_when: false
    - name: Display installed packages
      debug:
        var: pip_list.stdout_lines