--- # Ansible Playbook to configure a set of Raspberry PIs in a consistent and repeatable way
# Software installation and configuration
- hosts: security_service
  remote_user: "{{ user }}"
  become: yes
  become_user: "{{ user }}"
  vars:
    src_dir: "{{ playbook_dir }}"
    mode: u=rwx
  vars_files:
    - "{{ src_dir }}/conf/config.yaml"
  tasks:
    #################################################################
    ##### Windfire Security server component deployment Section #####
    #################################################################
    # Task 1: Delete Windfire Security directory on remote server
    - name: Remove "{{ remote_windfire_security_dir }}" directory and all its contents on remote server 
      ansible.builtin.file:
        path: "{{ remote_windfire_security_dir }}"
        state: absent
    
    # Task 2: Create Windfire Security directory on remote server and copy files
    - name: Copy Windfire Security server component to "{{ remote_windfire_security_dir }}" directory on remote server
      copy:
        src: "../../server"
        dest: "{{ remote_windfire_security_dir }}"
        owner: "{{ user }}"
        group: "{{ group }}"
        mode: "{{ mode }}"
    
    # Task 3: Copy setenv.sh to remote server
    - name: Copy setenv.sh to "{{ remote_windfire_security_dir }}" directory on remote server
      copy:
        src: "../../setenv.sh"
        dest: "{{ remote_windfire_security_dir }}"
        owner: "{{ user }}"
        group: "{{ group }}"
        mode: "{{ mode }}"

    # Task 4: Create Python virtual environment
    - name: Create Python virtual environment
      command:
        cmd: "{{ python_interpreter }} -m venv {{ venv_path }}"
        creates: "{{ venv_path }}/bin/activate"

    # Task 5: Verify virtualenv installation
    - name: Verify virtualenv is properly configured
      shell:
        cmd: "source {{ venv_path }}/bin/activate && python --version"
        executable: /bin/bash
      register: python_version
      changed_when: false
    
    - name: Display Python version in virtualenv
      debug:
        msg: "Python version in virtualenv: {{ python_version.stdout }}"
    
    # Task 6: Install required Python modules in virtualenv
    - name: Install required Python modules in virtualenv by running {{ install_python_modules_script }} install script
      shell: |
        source {{ venv_path }}/bin/activate
        bash {{ remote_windfire_security_dir }}/server/{{ install_python_modules_script }}
      args:
        executable: /bin/bash
    # - name: Install required Python modules in virtualenv
    #   pip:
    #     requirements: "{{ remote_windfire_security_dir }}/server/requirements.txt"
    #     virtualenv: "{{ venv_path }}"
    #     virtualenv_python: "{{ python_interpreter }}"
      
    # Task 7: List installed packages
    - name: List installed packages in virtualenv
      shell:
        cmd: "{{ venv_path }}/bin/pip list"
      register: pip_list
      changed_when: false
    
    - name: Display installed packages
      debug:
        var: pip_list.stdout_lines