--- # Ansible Playbook to configure a set of Raspberry PIs in a consistent and repeatable way
# Software installation and configuration for Raspberry PI box
- hosts: identitymanager
  remote_user: "{{ user }}"
  become: yes
  vars:
    src_dir: "{{ playbook_dir }}"
    mode: u=rwx
  vars_files:
    - "{{ src_dir }}/conf/raspberry-config.yml"
  tasks:
    - name: Ensure "{{ remote_directory }}" remote directory exists
      file:
        path: "{{ remote_directory }}"
        state: directory
    - name: Download Keycloak zip file
      get_url:
        url: "{{ keycloak_url }}"
        dest: "{{ keycloak_zip }}"
    - name: Unzip Keycloak to the remote directory
      unarchive:
        src: "{{ keycloak_zip }}"
        dest: "{{ remote_directory }}"
        remote_src: yes
        creates: "{{ remote_directory }}/keycloak-25.0.2"  # Ensures idempotency
    - name: Remove the downloaded zip file
      file:
        path: "{{ keycloak_zip }}"
        state: absent
    - name: Ensure "{{ remote_keycloak_utils_dir }}" remote directory exists
      file:
        path: "{{ remote_keycloak_utils_dir }}"
        state: directory
    - name: Copy Keycloak utility scripts "{{ remote_keycloak_utils_dir }}" folder on remote server
      copy:
        src: "./keycloak_scripts"
        dest: "{{ remote_keycloak_utils_dir }}"
        owner: "{{ user }}"
        group: "{{ group }}"
        mode: "{{ mode }}"